=== KookerFoxYT/NovaEngine-FNF/syntax/character.dtd
<!-- The character. Go figure. -->
<!ELEMENT character (anims,scale,scrollFactor,healthColor)>

	<!-- The type of atlas used for the character. -->
	<!ATTLIST character atlasType (SPARROW|PACKER|TEXTURE) #IMPLIED>
	
	<!-- The name of the character spritesheet. Looks in the `images/characters/` folder. -->
	<!ATTLIST character sprite CDATA #IMPLIED>
	
	<!-- Controls whether the object is smoothed when rotated, affects performance. Usually, you want
	this set to true for pixel characters. -->
	<!ATTLIST character antialiasing (false|true) #IMPLIED>
	
	<!-- Controls how long the character can hold down a note for before going back to idle. -->
	<!ATTLIST character singDuration CDATA #IMPLIED>
	
	<!-- The icon used for the health bar. -->
	<!ATTLIST character icon CDATA #IMPLIED>
	
	<!-- Flips the character horizontally if set to true. -->
	<!ATTLIST character flipX (false|true) #IMPLIED>
	
	<!-- Controls if the character acts like Boyfriend (Like only going back to idle when you release a
	note) -->
	<!ATTLIST character isPlayer (false|true) #IMPLIED>
	
	<!-- The character to load when you lose all of your health. -->
	<!ATTLIST character deathCharacter CDATA #IMPLIED>
	
	<!-- X. -->
	<!ATTLIST character x CDATA #IMPLIED>
	
	<!-- Y. -->
	<!ATTLIST character y CDATA #IMPLIED>
	
	<!-- The X offset of this character's camera position. -->
	<!ATTLIST character camX CDATA #IMPLIED>
	
	<!-- The Y offset of this character's camera position. -->
	<!ATTLIST character camY CDATA #IMPLIED>
	
	<!-- Allows you to have multiple animations when the character dances. -->
	<!ATTLIST character danceSteps CDATA #IMPLIED>

<!-- The animations. -->
<!ELEMENT anims (anim+)>

	<!-- An animation. -->
	<!ELEMENT anim EMPTY>

		<!-- The name of the animation. Examples include: idle, singLEFT, singRIGHTmiss -->
		<!ATTLIST anim name CDATA #REQUIRED>

		<!-- The name of the animation as defined by the spritesheet. -->
		<!ATTLIST anim anim CDATA #REQUIRED>

		<!-- The specific frames that the animation should play. -->
		<!ATTLIST anim indices CDATA #IMPLIED>

		<!-- The animation's framerate. -->
		<!ATTLIST anim fps CDATA #REQUIRED>

		<!-- Whether or not the animation should be looping when played. -->
		<!ATTLIST anim loop (false|true) #IMPLIED>

		<!-- Prevents the character from idling until the animation is done. -->
		<!ATTLIST anim specialAnim (false|true) #IMPLIED>

		<!-- X. -->
		<!ATTLIST anim x CDATA #REQUIRED>

		<!-- Y. -->
		<!ATTLIST anim y CDATA #REQUIRED>

<!-- The character's scale. -->
<!ELEMENT scale EMPTY>

	<!-- X. -->
	<!ATTLIST scale x CDATA #REQUIRED>

	<!-- Y. -->
	<!ATTLIST scale y CDATA #REQUIRED>

<!-- Basically paralax intensity. Figure that meaning out. :) -->
<!ELEMENT scrollFactor EMPTY>

	<!-- X. -->
	<!ATTLIST scrollFactor x CDATA #REQUIRED>

	<!-- Y. -->
	<!ATTLIST scrollFactor y CDATA #REQUIRED>

<!-- The character's health bar color. -->
<!ELEMENT healthColor EMPTY>
	
	<!-- Alternative is `hex`. -->
	<!ATTLIST healthColor rgb CDATA #IMPLIED>

	<!-- Alternative is `rgb`. -->
	<!ATTLIST healthColor hex CDATA #IMPLIED>

=== KookerFoxYT/NovaEngine-FNF/assets/data/characters/spooky/config.xml
<!DOCTYPE character SYSTEM "https://raw.githubusercontent.com/ThatOneIdiotXav/nova-basegame-actuallyfuckingfinished/main/syntax/character.dtd">
<character icon="spooky" sprite="spooky-kids" flipX="false" danceSteps="danceLeft,danceRight"
	y="200">
	<anims>
		<anim name="danceLeft" anim="spooky dance idle" indices="0,2,6" fps="12" loop="false" x="0"
			y="0" />
		<anim name="danceRight" anim="spooky dance idle" indices="8,10,12,14" fps="12" loop="false"
			x="0" y="0" />

		<anim name="singLEFT" anim="note sing left" indices="" fps="24" loop="false" x="130" y="-10" />
		<anim name="singDOWN" anim="spooky DOWN note" indices="" fps="24" loop="false" x="-50"
			y="-130" />
		<anim name="singUP" anim="spooky UP NOTE" indices="" fps="24" loop="false" x="-20" y="26" />
		<anim name="singRIGHT" anim="spooky sing right" indices="" fps="24" loop="false" x="-130"
			y="-14" />

		<anim name="hey" anim="spooky kids YEAH!!" fps="24" loop="false" x="59" y="-20" />
	</anims>

	<scale x="1" y="1" />
	<scrollFactor x="1" y="1" />

	<healthColor rgb="213, 126 ,0" />
</character>

=== KookerFoxYT/NovaEngine-FNF/assets/data/characters/monster/config.xml
<!DOCTYPE character SYSTEM "https://raw.githubusercontent.com/ThatOneIdiotXav/nova-basegame-actuallyfuckingfinished/main/syntax/character.dtd">
<character icon="monster" flipX="false" y="100">
	<anims>
		<anim name="idle" anim="monster idle" fps="24" loop="false" x="3" y="0" />

		<anim name="singLEFT" anim="Monster left note" fps="24" loop="false" x="-30" y="20" />
		<anim name="singDOWN" anim="monster down" fps="24" loop="false" x="-50" y="-80" />
		<anim name="singUP" anim="monster up note" fps="24" loop="false" x="-20" y="94" />
		<anim name="singRIGHT" anim="Monster Right note" fps="24" loop="false" x="-51" y="30" />
	</anims>

	<scale x="1" y="1" />
	<scrollFactor x="1" y="1" />

	<healthColor rgb="243,255,110" />
</character>

=== KookerFoxYT/NovaEngine-FNF/assets/data/characters/bf-dead/config.xml
<!DOCTYPE character SYSTEM "https://raw.githubusercontent.com/ThatOneIdiotXav/nova-basegame-actuallyfuckingfinished/main/syntax/character.dtd">
<character x="0" y="350" camX="0" camY="0" isPlayer="true" antialiasing="true" singDuration="4" deathCharacter="bf" icon="bf" flipX="true" danceSteps="idle" >
    <anims>
        <anim name="firstDeath" anim="BF dies" indices="" fps="24" loop="false" x="37" y="11" />
        <anim name="deathLoop" anim="BF Dead Loop" indices="" fps="24" loop="true" x="37" y="5" />
        <anim name="deathConfirm" anim="BF Dead confirm" indices="" fps="24" loop="false" x="37" y="69" />
    </anims>

    <scale x="1" y="1" />
    <scrollFactor x="1" y="1" />

    <healthColor rgb="49,176,209" />
</character>
